[package]
name = "zonecfg-backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
slog = "2.7.0"
slog-term = "2.9.0"
tar = "0.4.38"
zstd = "0.11.2"
